# Site settings
title: TJ VanToll's Blog
email: tj.vantoll@gmail.com
description: "TJ VanToll's blog about front-end technologies"
baseurl: ""
url: "https://www.tjvantoll.com"
excerpt_separator: <!--more-->

# Accounts
disqus_short_name: tjvantoll

# Build settings
markdown: kramdown
permalink: pretty
sass:
    style: :compressed