# Site settings
title: TJ VanToll's Blog
email: tj.vantoll@gmail.com
description: "TJ VanToll's blog about front-end technologies"
baseurl: ""
url: "https://www.tjvantoll.com"
excerpt_separator: <!--more-->
paginate: 10
paginate_path: "/blog/page:num/"

# Accounts
disqus_short_name: tjvantoll

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
permalink: pretty
sass:
    style: :compressed