# Site settings
title: TJ VanToll's Blog
email: tj.vantoll@gmail.com
description: "TJ VanToll's blog about front-end technologies"
baseurl: ""
url: "http://www.tjvantoll.com"
excerpt_separator: <!--more-->
paginate: 10

# Accounts
google_analytics_tracking_id: UA-29179796-1
disqus_short_name: tjvantoll

# Build settings
markdown: kramdown
permalink: pretty
sass:
    style: :compressed